# portal/app/urls.py
from django.urls import path

from .google_auth import login_with_google
from .login_auth import login, logout
from .me_view import me_view
from .commission_views import (
    CommissionRequestDetailView,
    CommissionRequestListView,
    CommissionSettlementListView,
    PenaltyRecordDetailView,
    PenaltyRecordListView,
    RefundRecordListView,
    RegulationSettlementRequestDetailView,
    RegulationSettlementRequestListView,
)
from .employee_views import (
    EmployeeArrivalConfirmView,
    EmployeeDocumentDeleteView,
    EmployeeDocumentUploadView,
    EmployeeFormOptionsView,
    EmployeeListCreateView,
    EmployeeOcrExtractView,
    EmployeeOcrStatusView,
    EmployeeProcessDeclineView,
    EmployeeProcessStartView,
    EmployeeReturnConfirmView,
    EmployeeReturnRequestApproveView,
    EmployeeReturnRequestRefuseView,
    EmployeeReturnRequestView,
    EmployeeReversalRequestApproveView,
    EmployeeReversalRequestRefuseView,
    EmployeeReversalRequestView,
    EmployeeRetrieveUpdateDestroyView,
    EmployeeSelectionView,
    EmployeeTravelBookingView,
    EmployeeTravelConfirmView,
)
from .registration_views import (
    company_superadmin_reset_token_consume,
    company_superadmin_reset_token_validate,
    csrf_token_view,
    password_reset_confirm,
    password_reset_request,
    public_auth_options_view,
    register,
    resend_verification,
    verify_email,
)
from .sync_views import (
    sync_organization_view,
    sync_plan_view,
    sync_subscription_view,
)
from .travel_views import TravelFlightAvailabilitySearchView, TravelLocationSearchView, TravelStatusView
from .platform_views import (
    AuditLogListView,
    CurrentOrganizationView,
    MarkAllNotificationsReadView,
    NotificationDetailView,
    NotificationListView,
    PlatformSettingsDetailView,
    UserPreferencesDetailView,
)
from .user_views import (
    StaffSideOptionsView,
    UserListCreateView,
    UserPasswordResetView,
    UserRetrieveUpdateDestroyView,
)

urlpatterns = [
    path("csrf/", csrf_token_view, name="csrf"),
    path("auth/options/", public_auth_options_view, name="auth-options"),
    path("login/", login, name="login"),
    path("auth/google/", login_with_google, name="auth-google"),
    path("logout/", logout, name="logout"),
    path("register/", register, name="register"),
    path("verify-email/", verify_email, name="verify-email"),
    path(
        "resend-verification/",
        resend_verification,
        name="resend-verification",
    ),
    path("password-reset/", password_reset_request, name="password-reset"),
    path(
        "password-reset/company-superadmin/validate/",
        company_superadmin_reset_token_validate,
        name="password-reset-company-superadmin-validate",
    ),
    path(
        "password-reset/company-superadmin/consume/",
        company_superadmin_reset_token_consume,
        name="password-reset-company-superadmin-consume",
    ),
    path(
        "password-reset/confirm/",
        password_reset_confirm,
        name="password-reset-confirm",
    ),
    path("me/", me_view, name="me"),
    path("employees/form-options/", EmployeeFormOptionsView.as_view(), name="employees-form-options"),
    path("employees/ocr/status/", EmployeeOcrStatusView.as_view(), name="employees-ocr-status"),
    path("employees/ocr/", EmployeeOcrExtractView.as_view(), name="employees-ocr"),
    path("employees/", EmployeeListCreateView.as_view(), name="employees-list"),
    path("employees/<int:pk>/", EmployeeRetrieveUpdateDestroyView.as_view(), name="employees-detail"),
    path("employees/<int:employee_pk>/selection/", EmployeeSelectionView.as_view(), name="employees-selection"),
    path("employees/<int:employee_pk>/process/", EmployeeProcessStartView.as_view(), name="employees-process-start"),
    path("employees/<int:employee_pk>/process/decline/", EmployeeProcessDeclineView.as_view(), name="employees-process-decline"),
    path("employees/<int:employee_pk>/return-request/", EmployeeReturnRequestView.as_view(), name="employees-return-request"),
    path("employees/<int:employee_pk>/return-request/approve/", EmployeeReturnRequestApproveView.as_view(), name="employees-return-request-approve"),
    path("employees/<int:employee_pk>/return-request/refuse/", EmployeeReturnRequestRefuseView.as_view(), name="employees-return-request-refuse"),
    path("employees/<int:employee_pk>/reversal-request/", EmployeeReversalRequestView.as_view(), name="employees-reversal-request"),
    path("employees/<int:employee_pk>/reversal-request/approve/", EmployeeReversalRequestApproveView.as_view(), name="employees-reversal-request-approve"),
    path("employees/<int:employee_pk>/reversal-request/refuse/", EmployeeReversalRequestRefuseView.as_view(), name="employees-reversal-request-refuse"),
    path("employees/<int:employee_pk>/travel-booking/", EmployeeTravelBookingView.as_view(), name="employees-travel-booking"),
    path("employees/<int:employee_pk>/travel-confirm/", EmployeeTravelConfirmView.as_view(), name="employees-travel-confirm"),
    path("employees/<int:employee_pk>/arrival-confirm/", EmployeeArrivalConfirmView.as_view(), name="employees-arrival-confirm"),
    path("employees/<int:employee_pk>/return-confirm/", EmployeeReturnConfirmView.as_view(), name="employees-return-confirm"),
    path("employees/<int:employee_pk>/documents/", EmployeeDocumentUploadView.as_view(), name="employees-document-upload"),
    path("employee-documents/<int:pk>/", EmployeeDocumentDeleteView.as_view(), name="employees-document-delete"),
    path("candidates/form-options/", EmployeeFormOptionsView.as_view(), name="candidates-form-options"),
    path("candidates/ocr/status/", EmployeeOcrStatusView.as_view(), name="candidates-ocr-status"),
    path("candidates/ocr/", EmployeeOcrExtractView.as_view(), name="candidates-ocr"),
    path("candidates/", EmployeeListCreateView.as_view(), name="candidates-list"),
    path("candidates/<int:pk>/", EmployeeRetrieveUpdateDestroyView.as_view(), name="candidates-detail"),
    path("candidates/<int:employee_pk>/selection/", EmployeeSelectionView.as_view(), name="candidates-selection"),
    path("candidates/<int:employee_pk>/process/", EmployeeProcessStartView.as_view(), name="candidates-process-start"),
    path("candidates/<int:employee_pk>/process/decline/", EmployeeProcessDeclineView.as_view(), name="candidates-process-decline"),
    path("candidates/<int:employee_pk>/return-request/", EmployeeReturnRequestView.as_view(), name="candidates-return-request"),
    path("candidates/<int:employee_pk>/return-request/approve/", EmployeeReturnRequestApproveView.as_view(), name="candidates-return-request-approve"),
    path("candidates/<int:employee_pk>/return-request/refuse/", EmployeeReturnRequestRefuseView.as_view(), name="candidates-return-request-refuse"),
    path("candidates/<int:employee_pk>/reversal-request/", EmployeeReversalRequestView.as_view(), name="candidates-reversal-request"),
    path("candidates/<int:employee_pk>/reversal-request/approve/", EmployeeReversalRequestApproveView.as_view(), name="candidates-reversal-request-approve"),
    path("candidates/<int:employee_pk>/reversal-request/refuse/", EmployeeReversalRequestRefuseView.as_view(), name="candidates-reversal-request-refuse"),
    path("candidates/<int:employee_pk>/travel-booking/", EmployeeTravelBookingView.as_view(), name="candidates-travel-booking"),
    path("candidates/<int:employee_pk>/travel-confirm/", EmployeeTravelConfirmView.as_view(), name="candidates-travel-confirm"),
    path("candidates/<int:employee_pk>/arrival-confirm/", EmployeeArrivalConfirmView.as_view(), name="candidates-arrival-confirm"),
    path("candidates/<int:employee_pk>/return-confirm/", EmployeeReturnConfirmView.as_view(), name="candidates-return-confirm"),
    path("candidates/<int:employee_pk>/documents/", EmployeeDocumentUploadView.as_view(), name="candidates-document-upload"),
    path("candidate-documents/<int:pk>/", EmployeeDocumentDeleteView.as_view(), name="candidates-document-delete"),
    path("commissions/requests/", CommissionRequestListView.as_view(), name="commissions-requests-list"),
    path("commissions/requests/<int:pk>/", CommissionRequestDetailView.as_view(), name="commissions-requests-detail"),
    path("commissions/settlements/", CommissionSettlementListView.as_view(), name="commissions-settlements-list"),
    path("commissions/regulation-requests/", RegulationSettlementRequestListView.as_view(), name="commissions-regulation-requests-list"),
    path("commissions/regulation-requests/<int:pk>/", RegulationSettlementRequestDetailView.as_view(), name="commissions-regulation-requests-detail"),
    path("commissions/refunds/", RefundRecordListView.as_view(), name="commissions-refunds-list"),
    path("commissions/penalties/", PenaltyRecordListView.as_view(), name="commissions-penalties-list"),
    path("commissions/penalties/<int:pk>/", PenaltyRecordDetailView.as_view(), name="commissions-penalties-detail"),
    path("travel/status/", TravelStatusView.as_view(), name="travel-status"),
    path("travel/locations/", TravelLocationSearchView.as_view(), name="travel-locations"),
    path("travel/flight-availabilities/", TravelFlightAvailabilitySearchView.as_view(), name="travel-flight-availabilities"),
    path("users/", UserListCreateView.as_view(), name="users-list"),
    path("users/staff-side-options/", StaffSideOptionsView.as_view(), name="users-staff-side-options"),
    path("users/<int:pk>/reset-password/", UserPasswordResetView.as_view(), name="users-reset-password"),
    path("users/<int:pk>/", UserRetrieveUpdateDestroyView.as_view(), name="users-detail"),
    path(
        "notifications/mark-all-read/",
        MarkAllNotificationsReadView.as_view(),
        name="notifications-mark-all-read",
    ),
    path(
        "notifications/<int:pk>/",
        NotificationDetailView.as_view(),
        name="notifications-detail",
    ),
    path("notifications/", NotificationListView.as_view(), name="notifications-list"),
    path(
        "preferences/me/",
        UserPreferencesDetailView.as_view(),
        name="preferences-me",
    ),
    path("organization/me/", CurrentOrganizationView.as_view(), name="organization-me"),
    path("company-sync/plans/", sync_plan_view, name="company-sync-plans"),
    path("company-sync/organizations/", sync_organization_view, name="company-sync-organizations"),
    path("company-sync/subscriptions/", sync_subscription_view, name="company-sync-subscriptions"),
    path(
        "platform-settings/",
        PlatformSettingsDetailView.as_view(),
        name="platform-settings",
    ),
    path("audit-logs/", AuditLogListView.as_view(), name="audit-logs-list"),
]
