# Generated by Django 6.0.3 on 2026-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_organization_productplan_profile_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_reference',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='company_reference',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productplan',
            name='company_reference',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
